name: mask_selector

# Masking schedules
restype_masking_schedule: "uniform_sqrt_t"

# Configs
restype_masking_cfg:
  uniform_t:
    t_min: 0.0
    t_max: 1.0
  constant_t:
    t: 0.0
  uniform_squared_t:
    t_min: 0.0
    t_max: 1.0
  uniform_cubed_t:
    t_min: 0.0
    t_max: 1.0
  uniform_cosine_t:
    t_min: 0.0
    t_max: 1.0
  uniform_sqrt_t:
    t_min: 0.0
    t_max: 1.0
  uniform_cbrt_t:
    t_min: 0.0
    t_max: 1.0
